# See here for image contents: https://github.com/microsoft/vscode-dev-containers/blob/v0.185.0/containers/python-3/.devcontainer/base.Dockerfile
ARG VARIANT="3"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
